#!/usr/bin/env sh
# Download exercise GIFs for every library entry into src/data/media (gitignored)
# and write src/data/media.ts, a require map keyed by library id.
# Source: hasaneyldrm/exercises-dataset. Run once locally; CI runs it before prebuild.
set -eu
cd "$(dirname "$0")/.."
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
git clone --depth 1 -q https://github.com/hasaneyldrm/exercises-dataset "$tmp"
mkdir -p src/data/media
bun -e '
import lib from "./src/data/library.json";
import { copyFileSync, existsSync, writeFileSync } from "node:fs";
const src = process.argv[1];
const lines = [];
for (const e of lib) {
  const from = `${src}/videos/${e.gif}`;
  if (!existsSync(from)) continue;
  copyFileSync(from, `src/data/media/${e.id}.gif`);
  lines.push(`  "${e.id}": require("./media/${e.id}.gif"),`);
}
writeFileSync("src/data/media.ts", `// Generated by scripts/fetch-media.sh. Do not edit.\nexport const MEDIA: Record<string, number> = {\n${lines.join("\n")}\n};\n`);
console.log(lines.length, "gifs");
' "$tmp"
